name: TonTin
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#environment:
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^1.2.0
  #encrypt: ^2.2.0
  pointycastle: ^1.0.1
  hex: ^0.1.2
  cipher2: 0.3.0
  drawerbehavior: ^0.0.4
  badges: ^0.0.6
  toast: ^0.1.4
  dio: ^2.1.3
  #fancy_bottom_navigation: ^0.1.0
  #json_annotation: ^1.2.0
  #json_serializable: ^1.3.0
  progress_hud: ^1.1.0
  shared_preferences: ^0.5.2
  liquid_pull_to_refresh: ^1.1.1
  sticky_headers: "^0.1.8"
  rflutter_alert: ^1.0.3
  vibrate: ^0.0.4
  local_auth: ^0.6.0+1
  cloud_firestore: ^0.12.9
  firebase_core: ^0.4.0+8
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  image_picker_saver: ^0.3.0
  intl: ^0.16.0
  flutter_screenutil: ^0.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^1.3.0
  flutter_datetime_picker: ^1.2.8
  carousel_slider: ^1.3.0



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/alucard.jpg
  - assets/money.png
  - assets/phone.jpg
  - assets/bag.jpg
  - assets/computer.jpg
  - assets/dress.jpg
  - assets/shoes.jpg
  - assets/image_01.png
  - assets/image_02.jpg
  - assets/image_03.jpg
  - assets/image_04.jpg

  fonts:
  - family: Nunito
    fonts:
    - asset: assets/Nunito.ttf

  - family: SF-Pro-Text-Regular
    fonts:
    - asset: assets/SF-Pro-Text-Regular.otf

  - family: SF-Pro-Text-Bold
    fonts:
    - asset: assets/SF-Pro-Text-Bold.otf

  - family: Calibre-Semibold
    fonts:
    - asset: assets/Calibre Semibold.otf

  - family: CustomIcons
    fonts:
    - asset: assets/custom_icons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
